import type { Metadata } from "next";
import { Roboto, Lexend } from "next/font/google";
import "./globals.css";



const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: "400"
})

const lexend = Lexend({
  variable: "--font-lexend",
  weight: "300",
  style: ["normal"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${lexend.variable} bg-d-nude antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
